import test from 'node:test';import assert from 'node:assert/strict';
import {selectGoogleForecast,googlePoints,matchedForecastValues,HOUR} from '../src/weatherComparisonData.js';
export const now=Date.parse('2026-09-05T22:00Z');
export function feedFixture(){
 const p={id:'knightdale',name:'Knightdale / Raleigh',latitude:35.787,longitude:-78.4806,timeZone:'America/New_York'};
 const make=(run,count,station=false)=>({status:'ready',runAt:new Date(run).toISOString(),fetchedAt:new Date(now-60000).toISOString(),points:[{...p,hourly:Array.from({length:count},(_,i)=>{const time=run+(i+1)*HOUR;const v=station?{station_head_temperature_2m:297+Math.sin(i/7),station_head_dewpoint_temperature_2m:291}:{temperature_2m:300+Math.sin(i/7),dewpoint_temperature_2m:293,wind_speed_10m:3,total_precipitation_1hr:.000254,total_cloud_cover:.85,mean_sea_level_pressure:101325,surface_solar_radiation_downwards_1hr:360000,u_component_of_wind_10m:0,v_component_of_wind_10m:-3};return {time:new Date(time).toISOString(),values:Object.fromEntries(Object.entries(v).map(([k,n])=>[k,{mean:n,p10:n-1,p90:n+1}]))};})}]});
 return {points:[p],sources:{surface:make(now-10*HOUR,360),interimSurface:make(now-HOUR,48),station:make(now-10*HOUR,360,true),interimStation:make(now-HOUR,48,true)}};
}
test('freshest applicable run, then main beyond interim horizon',()=>{const x=selectGoogleForecast(feedFixture(),'knightdale',now);assert.equal(x.rows.find(r=>r.epoch===now).provenance.id,'interimSurface');assert.equal(x.rows.find(r=>r.epoch===now+49*HOUR).provenance.id,'surface');});
test('matching station head supplies temperature and dew point',()=>{const r=selectGoogleForecast(feedFixture(),'knightdale',now).rows.find(r=>r.epoch===now);assert.ok(Math.abs(r.temperature-74.93)<.001);assert.match(r.temperatureSource,/station-trained/);assert.equal(r.pop,null);assert.equal(r.gust,null);assert.equal(r.uvIndex,null);});
test('mismatched station initialization cannot silently replace the surface run',()=>{const f=feedFixture();f.sources.interimStation.runAt=new Date(now-2*HOUR).toISOString();const r=selectGoogleForecast(f,'knightdale',now).rows.find(r=>r.epoch===now);assert.match(r.temperatureSource,/surface/);assert.ok(Math.abs(r.temperature-80.33)<.001);});
test('precipitation belongs to its actual interval, zeros preserved and missing stays missing',()=>{const f=feedFixture();const rows=f.sources.interimSurface.points[0].hourly;rows[0].values.total_precipitation_1hr.mean=.00254;rows[1].values.total_precipitation_1hr.mean=0;delete rows[2].values.total_precipitation_1hr;const x=selectGoogleForecast(f,'knightdale',now);const a=x.rows.find(r=>r.epoch===now),b=x.rows.find(r=>r.epoch===now+HOUR);assert.equal(a.precipitation,0);assert.equal(a.precedingPrecipitation,.1);assert.equal(b.precipitation,null);assert.equal(a.precipitationEnd,new Date(now+HOUR).toISOString());});
test('unknown locations rejected instead of nearest-point substitution',()=>{assert.throws(()=>selectGoogleForecast(feedFixture(),'raleigh-address',now),/no published forecast/);assert.throws(()=>googlePoints({}),/unavailable/);});
test('no invented missing values and no future-initialized runs',()=>{const f=feedFixture();f.sources.interimSurface.runAt=new Date(now+HOUR).toISOString();const r=selectGoogleForecast(f,'knightdale',now).rows.find(r=>r.epoch===now);assert.equal(r.provenance.id,'surface');});
test('comparisons require the identical valid timestamp',()=>{const t=new Date(now+HOUR).toISOString(),a={hours:[{time:t}]};assert.equal(matchedForecastValues(a,{hours:[{time:new Date(now+HOUR+60000).toISOString()}]},now),null);assert.equal(matchedForecastValues(a,a,now).time,t);});
