const DIRECTORY_SOURCE = "Fuel IQ corporate distributor index";
export const KNOWN_COMPANIES = [
  ["Tiger Fuel Company",["tiger fuel","tiger fuel co","tiger fuel company"],"Charlottesville, Virginia","https://tigerfuel.com/"],
  ["J.H. Seale & Son, Inc.",["jh seale","j h seale","j.h. seale"],"Sumter, South Carolina","https://jhseale.com/"],
  ["Mansfield Energy Corp.",["mansfield","mansfield energy","mansfield oil"],"Gainesville, Georgia","https://www.mansfield.energy/"],
  ["TACenergy, LLC",["tacenergy","tac energy","tacenergy llc"],"Dallas, Texas","https://www.tacenergy.com/"],
  ["Petroleum Traders Corporation",["petroleum traders","petroleum traders corporation","ptc fuel"],"Fort Wayne, Indiana","https://www.petroleumtraders.com/"],
  ["Pilot Thomas Logistics",["pilot thomas","pilot thomas logistics","ptl fuel"],"Fort Worth, Texas","https://www.pilotthomas.com/"],
  ["RelaDyne, LLC",["reladyne","rela dyne"],"Cincinnati, Ohio","https://reladyne.com/"],
  ["Offen Petroleum, LLC",["offen","offen petroleum","offen petro"],"Commerce City, Colorado","https://offenpetro.com/"],
  ["Sun Coast Resources, LLC",["sun coast resources","sun coast fuel","suncoast resources"],"Houston, Texas","https://www.suncoastresources.com/"],
  ["World Kinect Corporation",["world kinect","world fuel services","world fuel"],"Miami, Florida","https://www.world-kinect.com/"],
  ["Sunoco LP",["sunoco","sunoco lp"],"Dallas, Texas","https://www.sunocolp.com/"],
  ["Global Partners LP",["global partners","global partners lp","global petroleum"],"Waltham, Massachusetts","https://www.globalp.com/"],
  ["Sprague Operating Resources LLC",["sprague","sprague energy","sprague operating resources"],"Portsmouth, New Hampshire","https://www.spragueenergy.com/"],
  ["Atlas Oil Company",["atlas oil","atlas oil company"],"Taylor, Michigan","https://www.atlasoil.com/"],
  ["U.S. Venture, Inc.",["us venture","u.s. venture","us oil"],"Appleton, Wisconsin","https://www.usventure.com/"],
  ["Guttman Energy, Inc.",["guttman","guttman energy"],"Belle Vernon, Pennsylvania","https://www.guttmanenergy.com/"],
  ["Shipley Energy Company",["shipley energy","shipley fuel"],"York, Pennsylvania","https://www.shipleyenergy.com/"],
  ["Mirabito Holdings, Inc.",["mirabito","mirabito energy","mirabito fuel"],"Binghamton, New York","https://www.mirabito.com/"],
  ["Great Lakes Petroleum Co.",["great lakes petroleum","great lakes fuel"],"Charlotte, North Carolina","https://www.greatlakespetroleum.com/"],
  ["Petroleum Marketing Group, Inc.",["petroleum marketing group","pmg","pmg fuels"],"Woodbridge, Virginia","https://www.pmgfuels.com/"],
  ["James River Petroleum, Inc.",["james river petroleum","jrp fuel"],"Ashland, Virginia","https://www.jamesriverpetroleum.com/"],
  ["Colonial Oil Industries, Inc.",["colonial oil industries","colonial oil","colonial fuel"],"Savannah, Georgia","https://www.colonialoilindustries.com/"],
  ["Walthall Oil Company",["walthall oil","walthall"],"Macon, Georgia","https://www.walthalloil.com/"],
  ["McPherson Oil Companies",["mcpherson oil","mcpherson oil companies"],"Trussville, Alabama","https://www.mcphersonoil.com/"],
  ["Southeast Petro Distributors, Inc.",["southeast petro","southeast petroleum","southeast petro distributors"],"Cocoa, Florida","https://www.southeastpetro.com/"],
  ["Palmdale Oil Company, Inc.",["palmdale oil","palmdale oil company"],"Fort Pierce, Florida","https://www.palmdaleoil.com/"],
  ["Port Consolidated, Inc.",["port consolidated","port fuel"],"Fort Lauderdale, Florida","https://www.portconsolidated.com/"],
  ["Boyett Petroleum",["boyett","boyett petroleum"],"Modesto, California","https://boyett.net/"],
  ["Hunt & Sons, Inc.",["hunt and sons","hunt & sons","hunt fuel"],"Sacramento, California","https://www.huntnsons.com/"],
  ["Ramos Oil Company",["ramos oil","ramos oil company"],"West Sacramento, California","https://www.ramosoil.com/"],
  ["Coleman Oil Company",["coleman oil","coleman oil company"],"Lewiston, Idaho","https://www.colemanoil.com/"],
  ["Ed Staub & Sons",["ed staub","ed staub and sons","staub fuel"],"Klamath Falls, Oregon","https://www.edstaub.com/"],
  ["Senergy Petroleum",["senergy","senergy petroleum"],"Phoenix, Arizona","https://www.senergypetroleum.com/"],
  ["Corrigan Oil Company",["corrigan oil","corrigan oil company"],"Brighton, Michigan","https://www.corriganoil.com/"],
  ["Jacobus Energy, LLC",["jacobus","jacobus energy"],"Milwaukee, Wisconsin","https://www.jacobusenergy.com/"],
  ["MFA Oil Company",["mfa oil","mfa oil company"],"Columbia, Missouri","https://www.mfaoil.com/"],
  ["CHS Inc.",["chs","cenex","chs refined fuels"],"Inver Grove Heights, Minnesota","https://www.chsinc.com/"],
  ["GROWMARK, Inc.",["growmark","fs energy","growmark energy"],"Bloomington, Illinois","https://www.growmark.com/"],
  ["CountryMark",["countrymark","country mark"],"Indianapolis, Indiana","https://www.countrymark.com/"],
  ["Southern States Cooperative",["southern states","southern states cooperative"],"Richmond, Virginia","https://www.southernstates.com/"],
  ["Douglass Distributing",["douglass distributing","douglass fuel","douglass petroleum"],"Sherman, Texas","https://www.douglassdistributing.com/"],
  ["Martin Eagle Oil Company",["martin eagle oil","martin eagle","meo fuel"],"Denton, Texas","https://www.martineagleoil.com/"],
  ["Tri Star Energy, LLC",["tri star energy","tristar energy","tri star fuel"],"Nashville, Tennessee","https://www.tristartn.com/"],
  ["Dearybury Oil & Gas Company",["dearybury","dearybury oil","dearybury oil and gas"],"Spartanburg, South Carolina","https://www.dearybury.com/"],
  ["Majors Management, LLC",["majors management","majors fuel"],"Lawrenceville, Georgia","https://www.majorsmanagement.com/"],
  ["Carroll Motor Fuels",["carroll motor fuels","carroll fuels"],"Baltimore, Maryland","https://www.carrollfuel.com/"],
  ["Tevis Energy",["tevis energy","tevis oil","tevis fuel"],"Westminster, Maryland","https://www.tevisenergy.com/"],
  ["Dead River Company",["dead river","dead river company"],"South Portland, Maine","https://www.deadriver.com/"],
  ["Aloha Petroleum, Ltd.",["aloha petroleum","aloha gas"],"Honolulu, Hawaii","https://www.alohagas.com/"],
  ["Par Hawaii",["par hawaii","par petroleum hawaii"],"Honolulu, Hawaii","https://www.parhawaii.com/"],
  ["Petro 49, Inc.",["petro 49","petro49"],"Anchorage, Alaska","https://www.petro49.com/"],
  ["Crowley Fuels LLC",["crowley fuels","crowley fuel"],"Anchorage, Alaska","https://www.crowley.com/fuels/"],
  ["Delta Western, Inc.",["delta western","delta western fuel"],"Anchorage, Alaska","https://www.deltawestern.com/"],
  ["Cary Oil Co., Inc.",["cary oil","cary oil company"],"Cary, North Carolina","https://www.caryoil.com/"],
  ["ARKO Petroleum Corp.",["arko petroleum","arko fuel"],"Richmond, Virginia","https://www.arkopetroleum.com/"],
  ["Colonial Fuel & Lubricant Services, Inc.",["colonial fuel","colonial fuel and lubricant"],"Savannah, Georgia","https://colonialgroupinc.com/fuel-lubricants/"],
  ["Clipper Petroleum, Inc.",["clipper petroleum","clipper fuel"],"Flowery Branch, Georgia","https://www.clipperpetroleum.com/"],
  ["Valor Oil",["valor oil","valor oil company"],"Owensboro, Kentucky","https://valoroil.com/"],
  ["Lard Oil Company",["lard oil","lard oil company"],"Denham Springs, Louisiana","https://www.lardoil.com/"],
  ["Lott Oil Company",["lott oil","lott oil company"],"Natchitoches, Louisiana","https://lottoil.com/"],
  ["Waring Oil Company",["waring oil","waring oil company"],"Vicksburg, Mississippi","https://waringoil.com/"],
  ["PURE Oil Jobbers Cooperative, Inc.",["pure oil jobbers","pure oil cooperative","be sure with pure"],"Rock Hill, South Carolina","https://besurewithpure.com/"],
  ["Calloway Oil Company",["calloway oil","calloway oil company"],"Georgia","https://callowayoil.com/"],
  ["JAT Energy",["jat energy","jat oil"],"Chattanooga, Tennessee","https://jatoil.com/"],
  ["Hendry Oil Company",["hendry oil","hendry oil company"],"Nashville, Arkansas","https://hendryoilar.com/"],
  ["Stephenson Oil Company",["stephenson oil","stephenson oil company"],"North Little Rock, Arkansas","https://www.stephensonoilco.com/"],
  ["Red River Oil Company",["red river oil","red river oil company"],"Ashdown, Arkansas","https://www.redriveroilco.com/"],
  ["Sayle Oil Company",["sayle oil","sayle oil company"],"Mississippi","https://www.sayleoil.com/"],
  ["Best Wade Petroleum",["best wade","best wade petroleum","wade inc petroleum"],"Memphis, Tennessee","https://bestwade.com/"],
  ["Arnold Oil Company Fuels, LLC",["arnold oil","arnold oil company","arnold oil fuels"],"Austin, Texas","https://www.arnoldoil.com/"],
  ["Arguindegui Oil Co. II, Ltd.",["arguindegui oil","arguindegui","argpetro"],"San Antonio, Texas","https://argpetro.com/"],
  ["Davidson Oil Company",["davidson oil","davidson oil company"],"Amarillo, Texas","https://www.davidsonoil.com/"],
  ["Gaubert Oil Company, Inc.",["gaubert oil","gaubert oil company"],"Louisiana","https://www.gaubertoil.com/"],
  ["The Kent Companies",["kent oil","kent companies","the kent companies"],"Midland, Texas","https://kentcompanies.com/"],
  ["Reeder Distributors, Inc.",["reeder distributors","reeder fuel"],"Fort Worth, Texas","https://reederdistributors.com/"],
  ["Texas Enterprises, Inc.",["texas enterprises","texas enterprises fuel"],"Austin, Texas","https://texasenterprises.com/"],
  ["Bumgarner Oil Co., Inc.",["bumgarner oil","bumgarner oil company"],"Hickory, North Carolina","https://bumgarneroil.com/"],
  ["New Dixie Oil Corporation",["new dixie oil","new dixie"],"Roanoke Rapids, North Carolina","https://newdixieoil.com/"],
  ["Rex Oil Co.",["rex oil","rex oil company"],"Thomasville, North Carolina",""],
  ["Henderson Oil Company",["henderson oil","henderson oil company"],"Hendersonville, North Carolina","https://www.hendersonoil.com/"],
  ["Keenan Energy Company",["keenan energy","keenan energy company"],"The Carolinas","https://keenanenergy.com/"],
  ["Indigo Energy",["indigo energy","indigo petroleum"],"South Carolina","https://indigoenergy.com/"],
  ["Sommers Oil Company",["sommers oil","somco","somco inc"],"Georgia","https://sommersoil.com/"],
  ["Carroll Independent Fuel Company",["carroll independent fuel","carroll fuel company"],"Baltimore, Maryland","https://carrollfuel.com/"],
  ["The Wills Group, Inc.",["wills group","the wills group"],"La Plata, Maryland","https://www.willsgroup.com/"],
  ["John W. Stone Oil Distributor, LLC",["john w stone oil","stone oil distributor","jw stone"],"Gretna, Louisiana","https://www.jwstone.com/"],
  ["Retif Oil & Fuel, LLC",["retif oil","retif oil and fuel"],"Harvey, Louisiana","https://retifoil.com/"],
  ["Buchanan Oil Company",["buchanan oil","buchanan oil company","buchanan petroleum"],"",""],
  ["H.N. Funkhouser & Co.",["h n funkhouser","funkhouser oil","funkhouser fuel"],"",""],
  ["Holtzman Oil Corp.",["holtzman oil","holtzman fuel"],"",""],
  ["Quarles Petroleum",["quarles","quarles petroleum","quarles fleet fueling"],"",""],
  ["Tropic Oil Company",["tropic oil","tropic oil company"],"",""],
  ["SC Fuels",["sc fuels","southern counties oil"],"",""],
  ["W.H. Breshears, Inc.",["w h breshears","breshears fuel"],"",""],
  ["Christensen, Inc.",["christensen fuel","christensen inc"],"",""],
  ["Associated Petroleum Products, Inc.",["associated petroleum products","app fuel"],"",""],
  ["Kellerstrass Oil Company",["kellerstrass","kellerstrass oil"],"",""],
  ["Desert Fuels",["desert fuels","desert fuel"],"",""],
  ["Lakeside Oil Company",["lakeside oil","lakeside fuel"],"",""],
  ["Home Service Oil Company",["home service oil","home service fuel"],"",""],
  ["Wallis Companies",["wallis companies","wallis oil"],"",""],
  ["Co-Alliance Cooperative, Inc.",["co-alliance","co alliance","co alliance cooperative"],"",""],
  ["Petroleum Wholesale L.P.",["petroleum wholesale","petroleum wholesale lp"],"",""],
  ["McCraw Oil Company",["mccraw oil","mc craw oil"],"",""],
  ["Hollingsworth Oil Company",["hollingsworth oil","hollingsworth fuel"],"",""],
  ["Southwest Georgia Oil Company",["southwest georgia oil","swga oil"],"",""],
  ["Gate Petroleum Company",["gate petroleum","gate fuel"],"",""],
  ["Campbell Oil Company",["campbell oil","campbell fuel"],"",""],
  ["Parker Oil Company",["parker oil","parker fuel"],"",""],
  ["Griffith Energy Services",["griffith energy","griffith fuel"],"",""],
  ["Irving Energy",["irving energy","irving oil"],"",""],
  ["Hawaii Petroleum, LLC",["hawaii petroleum","makoil"],"",""],
  ["Jackson Energy",["jackson energy","jackson fuel"],"",""],
  ["Harms Oil Company",["harms oil","harms oil company"],"",""],
  ["Stern Oil Company",["stern oil","stern oil company"],"",""],
  ["Allied Oil & Supply, Inc.",["allied oil","allied oil and supply"],"",""],
  ["Yocum Oil Company",["yocum oil","yocum fuel"],"",""],
  ["Beaudry Oil & Propane",["beaudry oil","beaudry fuel"],"",""],
  ["Hightowers Petroleum Company",["hightowers petroleum","hightower petroleum"],"",""],
  ["Heritage Petroleum, LLC",["heritage petroleum","heritage fuel"],"",""],
  ["Rymes Propane & Oil",["rymes","rymes oil","rymes propane"],"",""],
  ["Haffner's",["haffners","haffner fuel","energy north"],"",""],
  ["Townsend Energy",["townsend energy","townsend oil"],"",""],
  ["Santa Energy",["santa energy","santa fuel"],"",""],
  ["D.F. Richard Energy",["df richard","d f richard energy"],"",""],
  ["Suburban Propane Partners, L.P.",["suburban propane","suburban fuel"],"",""],
  ["AmeriGas Propane, L.P.",["amerigas","amerigas propane"],"",""],
  ["Ferrellgas Partners, L.P.",["ferrellgas","ferrell gas"],"",""],
].map(([legal_name, aliases, headquarters = "", website = ""]) => ({
  legal_name,
  aliases,
  headquarters,
  website,
  description: "Known corporate fuel distributor or petroleum marketer; live verification checks the current legal entity, ownership, and headquarters.",
  distributor_types: [],
  parent_company: "",
  corporate_evidence: "Indexed by Fuel IQ as a corporate distributor, petroleum marketer, jobber, wholesale fuel supplier, or bulk-fuel supplier.",
  entity_type: "corporate_distributor",
  confidence: website ? "Corporate directory match" : "Corporate name-index match",
  source: DIRECTORY_SOURCE,
  source_url: website || "",
  directory_match: true,
}));
